import pandas as pd
from google import genai # Using the new, modern library!
import os

def clean_and_assess_data():
    print("🧹 1. Starting data cleaning...")
    df = pd.read_json('assets.json')
    df = df.drop_duplicates()
    
    df['Status'] = df['Status'].str.capitalize().replace('Actv', 'Active')
    df['MFA_Enabled'] = df['MFA_Enabled'].fillna(False)
    df['Encryption'] = df['Encryption'].fillna('Unencrypted')
    
    df.to_csv('cleaned_assets.csv', index=False)
    print("✅ Cleaning complete!")

    print("🕵️ 2. Hunting for security risks...")
    
    # Grab the API key from your computer
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("🚨 ERROR: We need a Gemini API Key to run the AI Assessor!")
        return
        
    # Initialize the modern Gemini Client
    client = genai.Client(api_key=api_key)
    risk_register = []

    for index, row in df.iterrows():
        if row['Status'] == 'Active' and (row['MFA_Enabled'] == False or row['Encryption'] in ['None', 'Unencrypted']):
            print(f"⚠️ Risk found on {row['AssetID']}! Asking AI for mitigation strategy...")
            
            prompt = f"""
            Act as a strict GRC Security Analyst. 
            We have an active asset with the following details:
            Asset ID: {row['AssetID']}
            Type: {row['Type']}
            MFA Enabled: {row['MFA_Enabled']}
            Encryption: {row['Encryption']}
            
            Write a very short, 2-sentence mitigation strategy to fix this compliance violation.
            """
            
            # Use the new generate_content syntax
            response = client.models.generate_content(
                model='gemini-2.5-flash', 
                contents=prompt
            )
            
            risk_register.append({
                "AssetID": row['AssetID'],
                "Owner": row['Owner'],
                "Vulnerability": "Missing MFA or Encryption",
                "AI_Mitigation_Plan": response.text.strip()
            })

    if risk_register:
        risk_df = pd.DataFrame(risk_register)
        risk_df.to_csv('risk_register.csv', index=False)
        print("✅ AI Assessment complete! Saved to risk_register.csv")
        
        # --- NEW CODE: GENERATE HTML WEBPAGE ---
        html_content = f"""
        <html>
        <head>
            <title>GRC AI Audit Report</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 40px; background-color: #f4f4f9; }}
                h1 {{ color: #333; }}
                table {{ border-collapse: collapse; width: 100%; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 8px rgba(0,0,0,0.1); }}
                th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
                th {{ background-color: #F6821F; color: white; }} /* Cloudflare Orange! */
            </style>
        </head>
        <body>
            <h1>🛡️ Automated GRC AI Audit Report</h1>
            <p>This risk register is automatically generated by an AI assessing company assets for missing security controls.</p>
            {risk_df.to_html(index=False, border=0)}
        </body>
        </html>
        """
        with open('index.html', 'w', encoding='utf-8') as f:
            f.write(html_content)
        print("🌐 Webpage generated as index.html!")
        
    else:
        print("🎉 No active risks found!")

if __name__ == "__main__":
    clean_and_assess_data()
